In [3]:
import pymongo
import pandas as pd
from pytz import timezone
from bson.codec_options import CodecOptions
import matplotlib.pyplot as plt
from pymongo import MongoClient
%matplotlib inline

#global const's
WEEKS = 8
TIMESTAMPS_PER_HOUR = 2
#global var's
local_client = MongoClient('localhost', 27017)
coll = local_client.admin.passwords
doc = coll.find_one({"key":"MONGOMLAB"})
mongopass = doc["value"]
client = MongoClient(f"mongodb://nailbiter:{mongopass}@ds149672.mlab.com:49672/logistics")

In [7]:
taskLog = pd.DataFrame(client.logistics["alex.taskLog"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo'))).find({"message":"add engage"}))
taskLog

,_id,date,message,obj
0,5d52c0a654765d6c28397f28,2019-08-13 22:52:37.853000+09:00,add engage,"{'pos': 22790143, 'due': None, 'shortUrl': 'ht..."
1,5d52c37340333b4104104f50,2019-08-13 23:04:35.525000+09:00,add engage,"{'pos': 1032192, 'due': None, 'shortUrl': 'htt..."
2,5d53769a40333b4104104f82,2019-08-14 11:48:58.852000+09:00,add engage,"{'pos': 524320, 'due': None, 'shortUrl': 'http..."
3,5d53ab2640333b4104104f91,2019-08-14 15:33:10.793000+09:00,add engage,"{'pos': 1032192, 'due': None, 'shortUrl': 'htt..."
4,5d54cf3c40333b4104104feb,2019-08-15 12:19:24.788000+09:00,add engage,"{'pos': 22790143, 'due': None, 'shortUrl': 'ht..."
...,...,...,...,...
1654,5f62f4c857566906a4e1ef95,2020-09-17 14:31:52.456000+09:00,add engage,"{'pos': 7929856, 'due': None, 'shortUrl': 'htt..."
1655,5f6301f557566906a4e1ef98,2020-09-17 15:28:05.238000+09:00,add engage,"{'pos': 524416, 'due': None, 'shortUrl': 'http..."
1656,5f6356f157566906a4e1efb8,2020-09-17 21:30:41.170000+09:00,add engage,"{'pos': 7864320, 'due': None, 'shortUrl': 'htt..."
1657,5f63e67557566906a4e1efd6,2020-09-18 07:43:01.669000+09:00,add engage,"{'pos': 671744, 'due': None, 'shortUrl': 'http..."
1658,5f64082e57566906a4e1efe9,2020-09-18 10:06:54.113000+09:00,add engage,"{'pos': 589824, 'due': '2020-09-18T01:30:52.40..."

In [38]:
from datetime import datetime, timedelta
_now = datetime.now()
_,_,wd = _now.isocalendar()
week_start = _now-timedelta(days=wd-1)
_df = taskLog[[d.date()>=week_start.date() for d in taskLog["date"]]]
_df = pd.DataFrame([{"date":r["date"],**r["obj"]} for r in _df.to_dict(orient="records")])
_df = _df.drop(columns=["id","idList","labels"])
_df["datetime"] = _df["date"]
_df["date"] = _df["date"].apply(lambda d:d.date())

_list = []
for date,chunk in _df.groupby("date"):
    _chunk = chunk.copy()
    _chunk["next_datetime"] = _chunk["datetime"].shift(-1)
    _chunk = _chunk[[not pd.isna(nd) for nd in _chunk["next_datetime"]]]
    _chunk["duration"] = (_chunk["next_datetime"] - _chunk["datetime"])
    _chunk["duration"] = _chunk["duration"].apply(lambda td:td.to_pytimedelta().total_seconds()/60/60)
    _list.append(_chunk)
_df = pd.concat(_list)

_df = _df[[n not in ["lunch"] for n in _df["name"]]]
_df.groupby("name").sum().sort_values(by="duration",ascending=False)

                      pos  dueComplete   duration
name
speed separation  1720576            0  14.503842
andy code          524416            0   7.512993
fix airflow prd    524544            0   1.525426