In [9]:
import pandas as pd
from os.path import splitext

df = pd.read_csv("/Users/nailbiter/Downloads/filelist.txt",sep="\t",header=None)
df

                                                         0
0                                     /media/pi/Transcend/
1                         /media/pi/Transcend/$RECYCLE.BIN
2        /media/pi/Transcend/$RECYCLE.BIN/S-1-5-21-2775...
3        /media/pi/Transcend/$RECYCLE.BIN/S-1-5-21-2775...
4                                 /media/pi/Transcend/alex
...                                                    ...
1939158  /media/pi/Transcend/System Volume Information/...
1939159                       /media/pi/Transcend/test.txt
1939160                 /media/pi/Transcend/TranscendElite
1939161  /media/pi/Transcend/TranscendElite/TranscendEl...
1939162  /media/pi/Transcend/TranscendElite/TranscendEl...

[1939163 rows x 1 columns]

In [21]:
df["ext"] = [splitext(fn)[1] for fn in df[0]]
df

                                                         0   ext
0                                     /media/pi/Transcend/
1                         /media/pi/Transcend/$RECYCLE.BIN  .BIN
2        /media/pi/Transcend/$RECYCLE.BIN/S-1-5-21-2775...
3        /media/pi/Transcend/$RECYCLE.BIN/S-1-5-21-2775...  .ini
4                                 /media/pi/Transcend/alex
...                                                    ...   ...
1939158  /media/pi/Transcend/System Volume Information/...  .dat
1939159                       /media/pi/Transcend/test.txt  .txt
1939160                 /media/pi/Transcend/TranscendElite
1939161  /media/pi/Transcend/TranscendElite/TranscendEl...  .dmg
1939162  /media/pi/Transcend/TranscendElite/TranscendEl...  .exe

[1939163 rows x 2 columns]

In [38]:
from itertools import chain
extensions_df = pd.read_csv("/Users/nailbiter/Downloads/audio_formats.csv",header=None)
extensions = pd.DataFrame({"ext":chain(*[[ee.strip() for ee in e.split(",")] for e in extensions_df[0]])}).set_index("ext")

music_df = pd.DataFrame({"path":extensions.join(df.set_index("ext"))[0]})
music_df = music_df.dropna()
music_df

                                                    path
ext
.3gp   /media/pi/Transcend/alex/alex2/alex/2010_02 Бу...
.3gp   /media/pi/Transcend/alex/alex2/alex/2010_02 Бу...
.3gp   /media/pi/Transcend/alex/alex2/alex/2010_02 Бу...
.3gp   /media/pi/Transcend/alex/alex2/alex/Fujisan/ta...
.aiff  /media/pi/Transcend/candice/学习/toefl 1/1 オーディ...
...                                                  ...
.wma   /media/pi/Transcend/Music/other/germancd/cd1/M...
.wma   /media/pi/Transcend/Music/other/germancd/cd1/M...
.wma   /media/pi/Transcend/Music/other/germancd/cd1/M...
.wma   /media/pi/Transcend/Music/other/germancd/cd1/M...
.wma   /media/pi/Transcend/Music/other/germancd/cd1/M...

[15791 rows x 1 columns]

In [44]:
with open("/Users/nailbiter/Downloads/mp3_tag2.sh","w") as f:
    n = len(music_df["path"])
    for i,p in enumerate(music_df["path"]):
        f.write(f"echo \"{p}\"\n")
        f.write(f">&2 date\n")
        f.write(f">&2 echo \"{i+1}/{n}\"\n")
        f.write(f"eyeD3 \"{p}\"\n")