In [1]:
from pymongo import MongoClient
import pandas as pd
import os
import tqdm
import itertools
import logging

client = MongoClient(f"mongodb+srv://nailbiter:{os.environ['MONGO_PASS']}@cluster0.gaq9o.mongodb.net/<dbname>?authSource=admin&replicaSet=atlas-1372ty-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true")

In [8]:
_df = pd.DataFrame(client.logistics["alex.paradigmTests"].find())
# print(_df.data.apply(len))
_df

,_id,data,topMostRow,leftMostColumn,name,id
0,5bc1979f2fe92c78b2a0e399,"[der, den, des, dem, die, die, der, der, das, ...","[M, F, N, Pl]","[N, A, G, D]",DUM,1
1,5bc1979f2fe92c78b2a0e39a,"[ein, einen, eines, einem, eine, eine, einer, ...","[M, F, N]","[N, A, G, D]",ein,2
2,5bc197a02fe92c78b2a0e39b,"[mein, meinen, meines, meinem, meine, meine, m...","[M, F, N, Pl]","[N, A, G, D]",mein,3
3,5bc197a02fe92c78b2a0e39c,"[e, en, en, en, e, e, en, en, e, e, en, en, en...","[M, F, N, Pl]","[N, A, G, D]",adj: definite article,4
4,5bc197a02fe92c78b2a0e39d,"[er, en, en, en, e, e, en, en, es, es, en, en,...","[M, F, N, Pl]","[N, A, G, D]",adj: Indefinite & Possessive Articles,5
5,5bc197a02fe92c78b2a0e39e,"[er, en, en, em, e, e, er, er, es, es, en, em,...","[M, F, N, Pl]","[N, A, G, D]",adj: No Article,6
6,5bc197a02fe92c78b2a0e39f,"[ich, du, er, sie, es, wir, ihr, sie, Sie, mic...","[N, A, D]","[I, you, he, she, it, we, you (pl), they, You]",pronouns,7
7,5bc197a12fe92c78b2a0e3a0,"[darf, darfst, darf, dürfen, dürft, dürfen, ka...","[allowance, ability, guess]","[ich, du, er/sie/es, wir, ihr, sie (Sie)]",dürfen/können/mögen,8
8,5bc197a12fe92c78b2a0e3a1,"[muss, musst, muss, müssen, müsst, müssen, sol...","[necessity, responsibility, forceful restriction]","[ich, du, er/sie/es, wir, ihr, sie (Sie)]",müssen/sollen,9
9,5bc197a12fe92c78b2a0e3a2,"[will, willst, will, wollen, wollt, wollen, mö...","[will, polite request]","[ich, du, er/sie/es, wir, ihr, sie (Sie)]",wollen/möchte,10
10,5bc197a12fe92c78b2a0e3a3,"[bin, bist, ist, sind, seid, sind]",[sind],"[ich, du, er/sie/es, wir, ihr, sie (Sie)]",sind,11
11,5bc197a12fe92c78b2a0e3a4,"[habe, hast, hat, haben, habt, haben]",[haben],"[ich, du, er/sie/es, wir, ihr, sie (Sie)]",haben,12
12,5bc197a12fe92c78b2a0e3a5,"[mein, dein, sein, ihr, unser, euer, ihr, mein...","[M, F, N, Pl]","[ich, du, er/es, sie, wir, ihr, sie/Sie]",pronouns Genitiv,13
13,5bc197a22fe92c78b2a0e3a6,"[könnte, könntest, könnte, könnten, könntet, k...","[können, sollen]","[ich, du, er/sie/es, wir, ihr, sie/Sie]",KONJUNKTIV II,14
14,5bfd34afd708060c84db3015,"[der, den, des, dem, die, die, der, der, das, ...","[M, F, N, Pl]","[N, A, G, D]",the,15

In [10]:
paradigm_tests = {}
assert len(_df)==_df["id"].nunique()
for r in (_df.to_dict(orient="records")):
    colnum,rownum = len(r["topMostRow"]),len(r["leftMostColumn"])
    data = r["data"]
    df = pd.DataFrame(
        index=r["leftMostColumn"],
        columns=r["topMostRow"],
        data=[[data[i+j*rownum] for j in range(colnum)] for i in range(rownum)],
    )
    paradigm_tests[r["name"]] = df
paradigm_tests = {k:v for k,v in paradigm_tests.items() if k not in ["DUM",]}
print(paradigm_tests.keys())
paradigm_tests["the"]

dict_keys(['ein', 'mein', 'adj: definite article', 'adj: Indefinite & Possessive Articles', 'adj: No Article', 'pronouns', 'dürfen/können/mögen', 'müssen/sollen', 'wollen/möchte', 'sind', 'haben', 'pronouns Genitiv', 'KONJUNKTIV II', 'the'])

     M    F    N   Pl
N  der  die  das  die
A  den  die  das  die
G  des  der  des  der
D  dem  der  dem  den

In [11]:
renamings = [
    {"N":"Nom","D":"Dat","G":"Gen","A":"Acc"},
    {"F":"Femi","M":"Masc","N":"Neut","Pl":"Plur"}
]
for k,df in paradigm_tests.items():
    for renaming in renamings:
        if set(list(df.index))<=set(renaming):
            logging.warning((k,",".join(list(renaming)),"index"))
            df.index = pd.Series(list(df.index)).apply(renaming.get)
        if set(list(df))<=set(renaming):
            logging.warning((k,",".join(list(renaming)),"col"))
            paradigm_tests[k] = df.rename(columns=renaming)
paradigm_tests["the"];

WARNING:root:('ein', 'N,D,G,A', 'index')
WARNING:root:('ein', 'F,M,N,Pl', 'col')
WARNING:root:('mein', 'N,D,G,A', 'index')
WARNING:root:('mein', 'F,M,N,Pl', 'col')
WARNING:root:('adj: definite article', 'N,D,G,A', 'index')
WARNING:root:('adj: definite article', 'F,M,N,Pl', 'col')
WARNING:root:('adj: Indefinite & Possessive Articles', 'N,D,G,A', 'index')
WARNING:root:('adj: Indefinite & Possessive Articles', 'F,M,N,Pl', 'col')
WARNING:root:('adj: No Article', 'N,D,G,A', 'index')
WARNING:root:('adj: No Article', 'F,M,N,Pl', 'col')
WARNING:root:('pronouns', 'N,D,G,A', 'col')
WARNING:root:('pronouns Genitiv', 'F,M,N,Pl', 'col')
WARNING:root:('the', 'N,D,G,A', 'index')
WARNING:root:('the', 'F,M,N,Pl', 'col')

In [12]:
for k,df in paradigm_tests.items():
    print(k)
    display(df)

ein

      Masc   Femi   Neut
Nom    ein   eine    ein
Acc  einen   eine    ein
Gen  eines  einer  eines
Dat  einem  einer  einem

mein

       Masc    Femi    Neut    Plur
Nom    mein   meine    mein   meine
Acc  meinen   meine    mein   meine
Gen  meines  meiner  meines  meiner
Dat  meinem  meiner  meinem  meinen

adj: definite article

    Masc Femi Neut Plur
Nom    e    e    e   en
Acc   en    e    e   en
Gen   en   en   en   en
Dat   en   en   en   en

adj: Indefinite & Possessive Articles

    Masc Femi Neut Plur
Nom   er    e   es   en
Acc   en    e   es   en
Gen   en   en   en   en
Dat   en   en   en   en

adj: No Article

    Masc Femi Neut Plur
Nom   er    e   es    e
Acc   en    e   es    e
Gen   en   er   en   er
Dat   em   er   em   en

pronouns

          Nom   Acc    Dat
I         ich  mich    mir
you        du  dich    dir
he         er   ihn    ihm
she       sie   sie    ihr
it         es    es    ihm
we        wir   uns    uns
you (pl)  ihr  euch   euch
they      sie   sie  ihnen
You       Sie   Sie  Ihnen

dürfen/können/mögen

          allowance ability  guess
ich            darf    kann    mag
du           darfst  kannst  magst
er/sie/es      darf    kann    mag
wir          dürfen  können  mögen
ihr           dürft   könnt   mögt
sie (Sie)    dürfen  können  mögen

müssen/sollen

          necessity, responsibility forceful restriction
ich                            muss                 soll
du                            musst               sollst
er/sie/es                      muss                 soll
wir                          müssen               sollen
ihr                           müsst                sollt
sie (Sie)                    müssen               sollen

wollen/möchte

             will polite request
ich          will         möchte
du         willst       möchtest
er/sie/es    will         möchte
wir        wollen        möchten
ihr         wollt        möchtet
sie (Sie)  wollen        möchten

sind

           sind
ich         bin
du         bist
er/sie/es   ist
wir        sind
ihr        seid
sie (Sie)  sind

haben

           haben
ich         habe
du          hast
er/sie/es    hat
wir        haben
ihr         habt
sie (Sie)  haben

pronouns Genitiv

          Masc    Femi   Neut    Plur
ich       mein   meine   mein   meine
du        dein   deine   dein   deine
er/es     sein   seine   sein   seine
sie        ihr    ihre    ihr    ihre
wir      unser  unsere  unser  unsere
ihr       euer    eure   euer    eure
sie/Sie    ihr    ihre    ihr    ihre

KONJUNKTIV II

             können    sollen
ich          könnte    sollte
du         könntest  solltest
er/sie/es    könnte    sollte
wir         könnten   sollten
ihr         könntet   solltet
sie/Sie     könnten   sollten

the

    Masc Femi Neut Plur
Nom  der  die  das  die
Acc  den  die  das  die
Gen  des  der  des  der
Dat  dem  der  dem  den

In [13]:
_df = pd.concat([
    pd.DataFrame([
        {
            "paradigm_name":name,
            "i":i,
            "j":j,
            "value":df.loc[i,j]
        }
        for i,j
        in itertools.product(df.index,list(df))
    ])
    for name,df
    in paradigm_tests.items()
])
_df = pd.DataFrame({"question":list(map(", ".join,zip(_df.paradigm_name,_df.i,_df.j))),"answer":_df["value"]})
_df.to_csv("/tmp/ef2dcd21_4d4d_46cc_918f_667aea3753f6.csv",index=None,sep="\t")
_df

          question answer
0   ein, Nom, Masc    ein
1   ein, Nom, Femi   eine
2   ein, Nom, Neut    ein
3   ein, Acc, Masc  einen
4   ein, Acc, Femi   eine
..             ...    ...
11  the, Gen, Plur    der
12  the, Dat, Masc    dem
13  the, Dat, Femi    der
14  the, Dat, Neut    dem
15  the, Dat, Plur    den

[213 rows x 2 columns]

In [14]:
pd.DataFrame([{"paradigm":k,"idx":",".join(sorted(list(v.index))),"col":",".join(sorted(list(v)))} for k,v in paradigm_tests.items()])

,paradigm,idx,col
0,ein,"Acc,Dat,Gen,Nom","Femi,Masc,Neut"
1,mein,"Acc,Dat,Gen,Nom","Femi,Masc,Neut,Plur"
2,adj: definite article,"Acc,Dat,Gen,Nom","Femi,Masc,Neut,Plur"
3,adj: Indefinite & Possessive Articles,"Acc,Dat,Gen,Nom","Femi,Masc,Neut,Plur"
4,adj: No Article,"Acc,Dat,Gen,Nom","Femi,Masc,Neut,Plur"
5,pronouns,"I,You,he,it,she,they,we,you,you (pl)","Acc,Dat,Nom"
6,dürfen/können/mögen,"du,er/sie/es,ich,ihr,sie (Sie),wir","ability,allowance,guess"
7,müssen/sollen,"du,er/sie/es,ich,ihr,sie (Sie),wir","forceful restriction,necessity, responsibility"
8,wollen/möchte,"du,er/sie/es,ich,ihr,sie (Sie),wir","polite request,will"
9,sind,"du,er/sie/es,ich,ihr,sie (Sie),wir",sind
10,haben,"du,er/sie/es,ich,ihr,sie (Sie),wir",haben
11,pronouns Genitiv,"du,er/es,ich,ihr,sie,sie/Sie,wir","Femi,Masc,Neut,Plur"
12,KONJUNKTIV II,"du,er/sie/es,ich,ihr,sie/Sie,wir","können,sollen"
13,the,"Acc,Dat,Gen,Nom","Femi,Masc,Neut,Plur"